defaults: &defaults
  maxmind:
    user_id: <%= ENV["MAXMIND_USER"] %>
    license_key: <%= ENV["MAXMIND_KEY"] %>
  five_hundred_px:
    api_key: <%= ENV["FIVEHUNDREDPX_KEY"] %>
  mapbox:
    token: <%= ENV["MAPBOX_TOKEN"] %>
  analytics:
    token: <%= ENV["ANALYTICS_KEY"] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
