# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 835eadcf296764726632932a53f7eb7d90b9e599c854f2c4652c0c41cadc19f87525350dee99fad649622ed366601ae10eac236795a71e5f205d63630b6f34c2

test:
  secret_key_base: a29ba4b7271f073c1bf32298c3b712fd0ef52de82a9bdb69fbda5349a73d9cc5165aab41da90662002c2fdad13ea0fee0a41541b742c975a6f9256a45714144c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["COOKIES_SECRET_BASE"] %>
